### ISSUE TITLE
Squid on bacterial genomes

### ISSUE THREAD

**Issue by tbarbier** [Kingsford-Group/squid#13]
Hi,

Is it possible to use SQUID to identify TSVs on RNA-seq data from bacteria?
I have been trying without success so far.
I tried to run SQUID on the BAM output from bwa mem but it raises the following message: "Assertion failed: (vNodes[i].Length>0 && vNodes[i].Position+vNodes[i].Length<=RefLength[vNodes[i].Chr]), function BuildNode_BWA, file src/SegmentGraph.cpp, line 1075. Abort trap: 6" 

I also tried to run SQUID using both -b alignment.bam and -c chimeric.bam (output from Samblaster) but this time it raises a Segmentation fault:11 error (previously reported [*](https://github.com/Kingsford-Group/squid/issues/4)).

Thanks for any help you could provide.

Best,

Thibault

**Comment by Congm12** [comment]
SQUID should be able to do that on bacteria, except that it assumes linear genome instead of circular one. Extra post-processing to remove the predictions that connect the end of genome to the beginning may be needed.

In terms of the error, would it be possible for you to share the input files? Without them, it is hard to track down the error.

**Comment by tbarbier** [comment]
Thank you very much for your answer and help.
Regarding the circular genome peculiarity, it makes a lot of sense and filtering should be straightforward.
Now in terms of the error, please find a link to download the bam files below along with a text file summarizing the history of the commands I used to generate these files and run SQUID if need be:
	- alignment.bam : https://www.dropbox.com/s/nkr83ytcctqtrk0/replicate1.bam?dl=0
	- splitreads.bam : https://www.dropbox.com/s/rlb68w36kp8799z/replicate1_splitreads.bam?dl=0
	- history of commands: https://www.dropbox.com/s/7hd8vuhjle8ed5z/Commands_history.txt?dl=0

Let me know if you cannot access the files or if you need anything.
Thanks again for your help!


Thibault

**Comment by Congm12** [comment]
With your alignment, you shouldn't use STAR version, since mapping quanlity in STAR and BWA are encoded differently.

Also, SQUID requires sorted alignment, so please sort your bam file with samtools sort before using SQUID.

Please checkout the newest release of SQUID, it fix bugs regarding one case of reading bam alignment record.

**Comment by tbarbier** [comment]
I just finished re-running Squid on my csorted .bam file and it worked! Thank you very much for your help. 
May I suggest to specify the requirement for a coordinate sorted bam as an input in the documentation? I know it is common practice but it could be helpful and does not appear in the --help or in the github readme.

Thanks again.

**Comment by Congm12** [comment]
It is a very good point. We updated the github readme page. Thanks for the suggestion.
